"""auto phone number

Revision ID: 2976e8604487
Revises: 9650ef87f45d
Create Date: 2022-08-03 19:11:24.563872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2976e8604487'
down_revision = '9650ef87f45d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
